theme: jekyll-theme-minimal
title: Vector-Quantized Timbre Representation
description: This webpage and repository host additional materials for this submission to ISMIR 2020. After the anonymized reviewing period, codes for our re-implementation of the perceptual audio loss will be merged into the final repository. Thank you for reading.
